version: '3.8'

services:
  service1:
    build:
      context: ./service1
    ports:
      - "8199:8199"
    networks:
      - net

  service2:
    build:
      context: ./service2
    networks:
      - net

networks:
  net:
    driver: bridge
